baseURL = "https://indoorfriends.netlify.app/"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Indoor Friends"
sectionPagesMenu = "main"
summaryLength = 15
pluralizelisttitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    description = "Meta Description goes here."
    images = ["meta-image.jpg"]
    googleTagManagerID = "GTM-xxxxxx"
    tiktok = "indoorfriends"
    pinterest = "indoorfriends"
    youtube = "indoorfriends"