baseURL = "https://indoorfriends.netlify.app/"
languageCode = "en-us"
title = "Indoor Friends"
sectionPagesMenu = "main"
summaryLength = 15
pluralizelisttitles = false

[params]
    description = "Meta Description goes here."
    images = ["meta-image.jpg"]
    googleTagManagerID = "GTM-xxxxxx"